
package com.powerlong.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceForPay", targetNamespace = "http://www.keytop.com.cn/", wsdlLocation = "http://192.168.121.254:8099/webserviceforpay.asmx?wsdl")
public class WebServiceForPay
    extends Service
{

    private final static URL WEBSERVICEFORPAY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WebServiceForPay.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WebServiceForPay.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.121.254:8099/webserviceforpay.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.121.254:8099/webserviceforpay.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEFORPAY_WSDL_LOCATION = url;
    }

    public WebServiceForPay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceForPay() {
        super(WEBSERVICEFORPAY_WSDL_LOCATION, new QName("http://www.keytop.com.cn/", "WebServiceForPay"));
    }

    /**
     * 
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap")
    public WebServiceForPaySoap getWebServiceForPaySoap() {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap"), WebServiceForPaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap")
    public WebServiceForPaySoap getWebServiceForPaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap"), WebServiceForPaySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap12")
    public WebServiceForPaySoap getWebServiceForPaySoap12() {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap12"), WebServiceForPaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap12")
    public WebServiceForPaySoap getWebServiceForPaySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap12"), WebServiceForPaySoap.class, features);
    }

}
