
package com.powerlong.webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "WebServiceForPaySoap", targetNamespace = "http://www.keytop.com.cn/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WebServiceForPaySoap {


    /**
     * 停车场信息接口
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingLotInfo", action = "http://www.keytop.com.cn/GetParkingLotInfo")
    @WebResult(name = "GetParkingLotInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingLotInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingLotInfo")
    @ResponseWrapper(localName = "GetParkingLotInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingLotInfoResponse")
    public String getParkingLotInfo();

    /**
     * 车流量查询接口
     *
     * @param startDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTrafficNum", action = "http://www.keytop.com.cn/GetTrafficNum")
    @WebResult(name = "GetTrafficNumResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetTrafficNum", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetTrafficNum")
    @ResponseWrapper(localName = "GetTrafficNumResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetTrafficNumResponse")
    public String getTrafficNum(
            @WebParam(name = "startDate", targetNamespace = "http://www.keytop.com.cn/")
            String startDate,
            @WebParam(name = "endDate", targetNamespace = "http://www.keytop.com.cn/")
            String endDate);

    /**
     * 停车费订单查询接口
     *
     * @param plateNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingPaymentInfo", action = "http://www.keytop.com.cn/GetParkingPaymentInfo")
    @WebResult(name = "GetParkingPaymentInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingPaymentInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingPaymentInfo")
    @ResponseWrapper(localName = "GetParkingPaymentInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingPaymentInfoResponse")
    public String getParkingPaymentInfo(
            @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
            String plateNo);

    /**
     * 停车费订单查询接口
     *
     * @param startTime
     * @param endTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPaymentInfoByTime", action = "http://www.keytop.com.cn/GetPaymentInfoByTime")
    @WebResult(name = "GetPaymentInfoByTimeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetPaymentInfoByTime", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetPaymentInfoByTime")
    @ResponseWrapper(localName = "GetPaymentInfoByTimeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetPaymentInfoByTimeResponse")
    public String getPaymentInfoByTime(
            @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
            String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
            String endTime);

    /**
     * 停车费订单查询接口(刷卡)
     *
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingPaymentInfoByCard", action = "http://www.keytop.com.cn/GetParkingPaymentInfoByCard")
    @WebResult(name = "GetParkingPaymentInfoByCardResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingPaymentInfoByCard", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingPaymentInfoByCard")
    @ResponseWrapper(localName = "GetParkingPaymentInfoByCardResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetParkingPaymentInfoByCardResponse")
    public String getParkingPaymentInfoByCard(
            @WebParam(name = "cardNo", targetNamespace = "http://www.keytop.com.cn/")
            String cardNo);

    /**
     * 入场车牌模糊查询接口
     *
     * @param pageSize
     * @param plateNo
     * @param pageIndex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFuzzyCarInfo", action = "http://www.keytop.com.cn/GetFuzzyCarInfo")
    @WebResult(name = "GetFuzzyCarInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetFuzzyCarInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetFuzzyCarInfo")
    @ResponseWrapper(localName = "GetFuzzyCarInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetFuzzyCarInfoResponse")
    public String getFuzzyCarInfo(
            @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
            String plateNo,
            @WebParam(name = "pageIndex", targetNamespace = "http://www.keytop.com.cn/")
            int pageIndex,
            @WebParam(name = "pageSize", targetNamespace = "http://www.keytop.com.cn/")
            int pageSize);

    /**
     * 停车费订单支付接口
     *
     * @param amount
     * @param orderNo
     * @param discount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee", action = "http://www.keytop.com.cn/PayParkingFee")
    @WebResult(name = "PayParkingFeeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.PayParkingFee")
    @ResponseWrapper(localName = "PayParkingFeeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.PayParkingFeeResponse")
    public String payParkingFee(
            @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
            String orderNo,
            @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
            int amount,
            @WebParam(name = "discount", targetNamespace = "http://www.keytop.com.cn/")
            int discount);

    /**
     * 按车牌查询停车信息接口
     *
     * @param startTime
     * @param pageCount
     * @param endTime
     * @param plateNo
     * @param pageIndex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarInOutInfoByPlate", action = "http://www.keytop.com.cn/GetCarInOutInfoByPlate")
    @WebResult(name = "GetCarInOutInfoByPlateResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarInOutInfoByPlate", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutInfoByPlate")
    @ResponseWrapper(localName = "GetCarInOutInfoByPlateResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutInfoByPlateResponse")
    public String getCarInOutInfoByPlate(
            @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
            String plateNo,
            @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
            String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
            String endTime,
            @WebParam(name = "pageIndex", targetNamespace = "http://www.keytop.com.cn/")
            int pageIndex,
            @WebParam(name = "pageCount", targetNamespace = "http://www.keytop.com.cn/")
            int pageCount);

    /**
     * 按出入口查询停车信息接口
     *
     * @param startTime
     * @param pageCount
     * @param leavePlace
     * @param entryPlace
     * @param endTime
     * @param pageIndex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarInOutInfoByPlace", action = "http://www.keytop.com.cn/GetCarInOutInfoByPlace")
    @WebResult(name = "GetCarInOutInfoByPlaceResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarInOutInfoByPlace", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutInfoByPlace")
    @ResponseWrapper(localName = "GetCarInOutInfoByPlaceResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutInfoByPlaceResponse")
    public String getCarInOutInfoByPlace(
            @WebParam(name = "entryPlace", targetNamespace = "http://www.keytop.com.cn/")
            String entryPlace,
            @WebParam(name = "leavePlace", targetNamespace = "http://www.keytop.com.cn/")
            String leavePlace,
            @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
            String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
            String endTime,
            @WebParam(name = "pageIndex", targetNamespace = "http://www.keytop.com.cn/")
            int pageIndex,
            @WebParam(name = "pageCount", targetNamespace = "http://www.keytop.com.cn/")
            int pageCount);

    /**
     * 订单状态查询接口
     *
     * @param orderNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPaymentStatus", action = "http://www.keytop.com.cn/GetPaymentStatus")
    @WebResult(name = "GetPaymentStatusResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetPaymentStatus", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetPaymentStatus")
    @ResponseWrapper(localName = "GetPaymentStatusResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetPaymentStatusResponse")
    public String getPaymentStatus(
            @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
            String orderNo);

    /**
     * 按第三方凭证查询停车信息接口
     *
     * @param startTime
     * @param pageCount
     * @param endTime
     * @param voucher
     * @param pageIndex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarInOutByVoucher", action = "http://www.keytop.com.cn/GetCarInOutByVoucher")
    @WebResult(name = "GetCarInOutByVoucherResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarInOutByVoucher", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutByVoucher")
    @ResponseWrapper(localName = "GetCarInOutByVoucherResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.powerlong.webService.client.GetCarInOutByVoucherResponse")
    public String getCarInOutByVoucher(
            @WebParam(name = "voucher", targetNamespace = "http://www.keytop.com.cn/")
            String voucher,
            @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
            String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
            String endTime,
            @WebParam(name = "pageIndex", targetNamespace = "http://www.keytop.com.cn/")
            int pageIndex,
            @WebParam(name = "pageCount", targetNamespace = "http://www.keytop.com.cn/")
            int pageCount);

}
